Fix "undefined reference to strl* when building iscsid"
Upstream's comment
=================
Are you doing make from the usr dir or from the open-iscsi root dir?
You have to do it from the open-iscsi root dir, because some stuff in
utils is needed by the stuff in usr. I suck at Makefile stuff so the
build system is crap :(